#version 460

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0, rgba8) uniform image2D srcImage;
layout(binding = 1, rgba8) uniform image2D dstImage;

void main() {
    ivec2 storePos = ivec2(gl_GlobalInvocationID.xy);

    // vec4 color = imageLoad(srcImage, storePos);
    // color.rgb = import_test() - color.rgb; // Invert colors

    imageStore(srcImage, storePos, vec4(1.0, 0.0, 0.0, 1.0));
    imageStore(dstImage, storePos, vec4(1.0, 0.0, 0.0, 1.0));
}